apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ws
  namespace: drawzy-prod
  labels:
    app:  ws
spec:
  replicas: 4
  selector:
    matchLabels:
      app:  ws
  template:
    metadata:
      labels:
        app:  ws
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: ws
      restartPolicy: Always 
      containers:
        - name: ws
          image:  ajayt8374/ws@sha256:0f2ad6f932045c623524310d25b14d5bee960311655bea5136375731fd5f9965
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 8080
          
          #Requests & Limits
          resources:
            requests:
              cpu:  "0.5"
              memory: "500Mi"
            limits:
              cpu:  "1"
              memory: "500Mi"
          
          # env variables 
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret 
                  key: JWT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret 
                  key: JWT_SECRET