apiVersion: v1 
kind: Service
metadata:
  name: drawzy-frontend-svc
  namespace:  drawzy-staging
spec:
  selector:
    app: drawzy-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: v1 
kind: Service
metadata:
  name: ws-svc
  namespace:  drawzy-staging
spec:
  type: ClusterIP
  selector:
    app:  ws 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1 
kind: Service 
metadata:
  name: postgres-svc
  namespace:  drawzy-staging
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app:  postgres