apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ws
  namespace: drawzy-staging
  labels:
    app:  ws
spec:
  replicas: 4
  selector:
    matchLabels:
      app:  ws
  template:
    metadata:
      labels:
        app:  ws
    spec:
      restartPolicy: Always 
      containers:
        - name: ws
          image: ajayt8374/ws@sha256:80047c400555a9da2143de76920fe6351a30a9f3ec163dd0ddcddd46f05593f5
          imagePullPolicy:  IfNotPresent
          ports:
            - containerPort: 8080
          
          #Requests & Limits
          resources:
            requests:
              cpu:  "0.5"
              memory: "500Mi"
            limits:
              cpu:  "1"
              memory: "500Mi"
          
          # env variables 
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret 
                  key: JWT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret 
                  key: JWT_SECRET